### ISSUE TITLE
Report cloud code javascript errors when deploy fails

### ISSUE THREAD

**Issue by nickoneill** [ParsePlatform/parse-cli#1]
The previous (non-go) version of the cli used to report errors and line numbers when cloud code js compile caused the deploy to fail. This is really useful, it'd be nice if this tool surfaced the same message.

**Comment by pavanka** [comment]
Thanks for the helpful suggestion.

You can see here https://github.com/ParsePlatform/parse-cli/blob/master/deploy_cmd.go#L439 that is just returns the error returned by the api server.

However to see errors & line numbers in cloud code js, you can just do `parse logs`, after that.
Now writing code to fetch logs can be messy because
1) what if it was a http error or some other non code compile related error, should I still show logs then?
2) while showing logs how many log lines should I fetch?

I'll investigate to see, if there is a nice way of doing this.

**Comment by nickoneill** [comment]
As far as I can tell, it doesn't surface that error from the API server to the user anywhere. If I'm using `develop` and introduce a syntax error and then save, the log shows no record of a failed deploy.

I'm not sure what the response is from the API server in this case (it might actually be the js error log, as it has been in the past) but a message when the deploy fails would be appreciated, even if it's just "deploy failed."

**Comment by pavanka** [comment]
definitely, note that develop pushes code to parse sever once a second, so you might have a lot of errors, we stopped surfacing errors, since otherwise your command prompt will get too noisy to be helpful. 

perhaps a better longer term solution to this would be to enable local development instead of pushing to parse servers, for instance you can use webhooks & a tunneling service like ngrok to let parse servers talk to your localhost, etc. ofcourse this assumes you are not using `parse hosted cloudcode`.

Here's a pull request: let me know if that looks good to you: https://github.com/ParsePlatform/parse-cli/pull/14

**Comment by pavanka** [comment]
fixed this for deploy. re-open if you meant develop. in which case it is pr-14

**Comment by nickoneill** [comment]
Thanks! This is great.
