### ISSUE TITLE
Parse auto-update and continuous integration

### ISSUE THREAD

**Issue by jmfayard** [ParsePlatform/parse-cli#3]
Hello, 
The auto-update feature that was introduced some time ago is very handy when we are developping, but does not play nice with the continuous integration

Background :
we put our cloud code in git repositories 
We have a bunch of hudson/jenkins that are triggered when a new commit is pushed to a given branch.
Each job does basically ` $ parse deploy $INSTANCE `
Which usually works, but sometimes mean actually, "try to update yourself, fail because we don't want to give you sudo rights on the CI machine, and even if we did, you would update yourself but not deploy the code"

**Comment by pavanka** [comment]
This seems to be an issue for xcode, homebrew as well.
Please look at https://github.com/ParsePlatform/parse-cli/blob/master/main.go#L383
You can set the env var PARSE_NOUPDATE=1 so it does not auto update.
however, that is not recommended. 

perhaps a better model would be supported versions instead of forcing one version all the time. Especially, to keep cli in sync with api server changes.
I'll write something to deal with supported versions in a few days.

**Comment by richardgroves** [comment]
This is an issue in standard cmd line usage too (on Mac OSX at least). Just issuing a normal command at the command line will hang if it tries to update as it doesn't have sudo privileges normally.

Please make it at least just spit out 'new version available' rather than forcing an update regardless of what command was issued.

**Comment by pavanka** [comment]
hence forth the releases will not have autoupdate functionality.
