### ISSUE TITLE
`parse develop` doesn't detect application from the current project folder.

### ISSUE THREAD

**Issue by nlutsenko** [ParsePlatform/parse-cli#38]
`parse deploy` - detects the application based on the `.parse.*` files in the current directory and deploys those.
`parse develop` - always asks for the application's name, dependless of the fact that you are already in the app's folder.

Not sure if we really want this, just throwing an idea - `parse develop` should detect this thing as well, since it's basically auto-deploy + log tailer.

cc @stanleyw

**Comment by nlutsenko** [comment]
Another thing on top of it - looks like CLI requires a case-sensitive name of the application to be specified.
Since case doesn't matter - if we don't go follow through with this - it might be a good idea to verify in every place that we don't require case-sensitive name.

**Comment by pavanka** [comment]
https://parse.com/docs/cloudcode/guide#command-line-developing-cloud-code

"Unlike the other commands, for develop you must specify the Parse App to push updates to. This is to avoid accidentally running develop on your production app causing you to run untested code in your production app."

That is intentional.

sure, it can be case insensitive. but could break existing clients. for instance I can have hello -> app_id1
Hello -> app_id2. if I make it case insensitive then it'll break current clients.

**Comment by nlutsenko** [comment]
Nvm then, sounds indeed intentional.
Maybe provide a confirmation for the current app if no app is specified?
The thing is - we have `parse deploy` which will deploy whatever you have in the current directory without any confirmation.

**Comment by pavanka** [comment]
That is true. Deploy is recoverable, because we remember 10 releases, so parse rollback will save us.
But with develop, we make so many deploys that rollback cannot help us. 
Anyway, I like the idea of `parse develop` with no options just asking for confirmation instead. I'll implement that function soon.

**Comment by pavanka** [comment]
https://github.com/ParsePlatform/parse-cli/commit/0ecfe8636d1cb4c342f1ae505cd395af8f1f5d58
