### ISSUE TITLE
Parse.com Cloud Code CLI gets stuck on logs

### ISSUE THREAD

**Issue by mitchellporter** [ParsePlatform/parse-cli#47]
I've been using `Parse.com's Cloud Code CLI` for a few weeks now and all of the sudden this started happening. I open up the terminal on my `iMac`, type `parse develop`, and press `ENTER` for default project name. It then proceeds to log a bunch of past logs and gets stuck. If I try to type in terminal I can, but it's not actually ready for a new command yet.

I looked up some help info in the CLI and tried using the following command to just prevent logs all together: `parse develop NAMEOFAPP --verbose`

However, when I enter that command, it proceeds to log all of my app's logs, and then gets stuck constantly logging the following 2 lines:

    This Not creating a release because no files have changed
    Uploading source files

It will literally keep logging those final 2 lines over and over and over. Not sure what is causing this. I have also tried deleting the CLI and re-installing but this has had no effect.

I have tested this on 2 separate `Parse.com` apps and they both reproduce the same results.

**Comment by pavanka** [comment]
Hey, this is an expected behavior, so develop uploads all changed files and tries to make a release every 1 second, and while making deploy if nothing changed, it will print that message, try setting this option
`interval=60s`, so it will only try to deploy every 60s but will nevertheless fetch the logs continuously (every 1s).
It is not stuck, just not getting any new logs for your apps, it could be an issue with the logging infrastructure. It is not an issue with the cli. Can you give me the names of your apps, so I can see if something is wrong with logging.

**Comment by mitchellporter** [comment]
Thanks for the fast response @pavanka. My current app I'm working on is called `SafeLife`

**Comment by pavanka** [comment]
@mitchellporter, I looked at the logs for your app.
I can definitely see logs for safelite, but the last of them were on nov 10th, either your did not use the app after that, or logging is broken for your app. If you feel it is the latter please open a bug report here: https://parse.com/help {look for 'open a ticket'}
Thanks.
